# Generated by Django 2.2 on 2019-12-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ID', models.TextField(max_length=50, primary_key=True, serialize=False)),
                ('Middle', models.TextField()),
                ('Modern_English', models.TextField()),
                ('Quote', models.TextField()),
                ('Line_Number', models.TextField(default='Line Number')),
                ('Contributor', models.TextField(default='Contributor')),
                ('Notes', models.TextField(default='Notes')),
                ('Language', models.TextField(default='')),
                ('Tags1', models.TextField(default='')),
                ('Tags2', models.TextField(default='')),
                ('Tags3', models.TextField(default='')),
                ('Tags4', models.TextField(default='')),
                ('TGNID', models.TextField(default='')),
                ('LatTGN', models.DecimalField(decimal_places=5, max_digits=15, null=True)),
                ('LongTGN', models.DecimalField(decimal_places=5, max_digits=15, null=True)),
                ('TGNURL', models.TextField(default='')),
                ('TGNT1', models.TextField(default='')),
                ('TGNT2', models.TextField(default='')),
                ('TGNT3', models.TextField(default='')),
                ('TGNT4', models.TextField(default='')),
                ('TGNT5', models.TextField(default='')),
                ('TGNT6', models.TextField(default='')),
                ('Collection', models.CharField(choices=[('Alliterative Morte Arthur', 'Art 8: Alliterative Morte Arthur'), ('Octavian', 'Art 10: Octavian'), ('Isumbras', 'Art 11: Isumbras'), ('Sir Degreuant', 'Art 15: Sir Degreuant')], default='Alliterative Morte Arthur', max_length=50)),
            ],
        ),
    ]
