# Generated by Django 2.2 on 2019-04-29 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_product_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='summary',
            new_name='Line_Number',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='Middle',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='Modern_English',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='Quote',
        ),
    ]
