# Generated by Django 2.2 on 2019-12-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191218_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ID',
        ),
        migrations.AddField(
            model_name='product',
            name='id',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False),
        ),
    ]
