# Generated by Django 2.2 on 2019-06-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190429_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Contributor',
            field=models.TextField(default='Contributor'),
        ),
        migrations.AddField(
            model_name='product',
            name='Language',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='Notes',
            field=models.TextField(default='Notes'),
        ),
        migrations.AddField(
            model_name='product',
            name='TGNID',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='TGNURL',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='Tags1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='Tags2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='Tags3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='Tags4',
            field=models.TextField(default=''),
        ),
    ]
