# Generated by Django 2.2 on 2019-07-05 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190615_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Collection',
            field=models.TextField(default='Alliterative Morte Arthur'),
        ),
    ]
