# Generated by Django 2.2 on 2019-12-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191218_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='LatTGN',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='LongTGN',
            field=models.TextField(default='', null=True),
        ),
    ]
