# Generated by Django 2.2 on 2019-08-02 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190718_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.IntegerField(choices=[(0, 'Regular'), (1, 'Manager'), (2, 'Admin')], default=0),
        ),
    ]
