# Generated by Django 2.2 on 2019-08-03 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.AlterField(
            model_name='product',
            name='Collection',
            field=models.IntegerField(choices=[(0, 'Regular'), (1, 'Manager'), (2, 'Admin')], default=0),
        ),
    ]
