# Generated by Django 2.2 on 2019-08-03 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190803_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Collection',
            field=models.IntegerField(choices=[(0, 'Art 8: Alliterative Morte Arthur'), (1, 'Art 10: Octavian'), (2, 'Art 11: Isumbras'), (3, 'Art 15: Sir Degreuant')], default=0),
        ),
    ]
